version: '3.8'

services:

  # Frontend Deploy
  easley-frontend:
    image: node:16
    working_dir: /usr/src/app/frontend
    command: bash -c "npm install; HTTPS=true npm start"
    volumes:
      - ./app/frontend:/usr/src/app/frontend
    ports:
      # 443 is default HTTPS port
      - 443:3000
    depends_on: 
      - easley-django

  # Django Deploy 
  easley-django:
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8009:8000
    env_file:
      - ./app/.env.dev
    depends_on: 
      - easley-db


  # Backend DB for Django
  easley-db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=dstreett
      - POSTGRES_PASSWORD=dstreett
      - POSTGRES_DB=easley_dev

volumes:
  postgres_data:
